### ISSUE TITLE
Test execution fails in Chrome Version 81.0.4044.129 (Official Build) (64-bit) browser.

### ISSUE THREAD

**Issue by jagadeeshshetty** [jagadeeshshetty/selenium-webdriver-demo#9]
**Framework version:** 1.7.0
**"chromedriver"**: "^79.0.0",

**Error:**
```bash
$ npm run test

> selenium-webdriver-demo@1.7.0 test C:\Users\jagadeesh\Documents\selenium-webdriver-demo
> node node_modules/mocha/bin/mocha



  Verify Dynamic Loading

DevTools listening on ws://127.0.0.1:59248/devtools/browser/c8aceca1-cc74-4ded-9ce4-90f7ab04267b
[212480:212472:0503/131454.046:ERROR:browser_switcher_service.cc(238)] XXX Init()
    1) "before each" hook for "hidden element"
    2) "after each" hook for "hidden element"


  0 passing (4s)
  2 failing

  1) "before each" hook for "hidden element":
     SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 79
      at Object.throwDecodedError (node_modules\selenium-webdriver\lib\error.js:550:15)
      at parseHttpResponse (node_modules\selenium-webdriver\lib\http.js:563:13)
      at Executor.execute (node_modules\selenium-webdriver\lib\http.js:489:26)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  2) "after each" hook for "hidden element":
     TypeError: Cannot read property 'quit' of undefined
      at DriverFactory.quit (lib\DriverFactory.js:13:27)
      at Context.<anonymous> (test\spec_helper.js:11:25)



npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! selenium-webdriver-demo@1.7.0 test: `node node_modules/mocha/bin/mocha`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the selenium-webdriver-demo@1.7.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jagadeesh\AppData\Roaming\npm-cache\_logs\2020-05-03T07_44_54_450Z-debug.log
```

**Comment by jagadeeshshetty** [comment]
I'll handle it.

**Comment by jagadeeshshetty** [comment]
_Reason:_
It's a Chrome driver version mismatch. Framework 1.7.0 version using 79.x.x version with chrome browser is 81.x.x version.

_Resolution:_
Update chromedriver version to the version which supports Chrome 81.x.x browser version.
